#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAIN-REPO_REPO == "MIAN-REPO" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0lST04tTUFOLUJPVC9JUk9OLUJBQ0stSEFORC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $MAIN-REPO_REPO == "MAIN-REPO" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0lST04tTUFOLUJPVC9JUk9OLUJBQ0stSEFORC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $MAIN-REPO_REPO =~ $regex ]]
    then
        if [[ $MAIN-REPO_REPO_BRANCH ]]
        then
            echo "${MAIN-REPO_REPO}/archive/${MAIN-REPO_REPO_BRANCH}.zip"
        else
            echo "${MAIN-REPO_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0lST04tTUFOLUJPVC9JUk9OLUJBQ0stSEFORC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="MIAN-REPO.zip"
    echo "  ⚜Downloading IRON-MAN-BOT V1.0⚜"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    IRONPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "CLEANING TRASH"
    rm -rf "$zippath"
    sleep 5
    cd $IRONPATH
    echo "    • Starting IRON-MAN-BOT•     "
    echo "
    IRON-MAN-BOT 
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
